#!/bin/sh

export ORGANISATION_NAME="Secret Keeper"
export SUFFIX="dc=secretkeeper,dc=com"
export ROOT_USER="admin"
export ROOT_PW="password"
export USER_UID="fgonzav"
export USER_GIVEN_NAME="Francisco"
export USER_SURNAME="González"
export USER_EMAIL="francisco@gmail.com"
export ACCESS_CONTROL="access to * by * read"
export LOG_LEVEL="stats"
